### ISSUE TITLE
.Add when collision happens

### ISSUE THREAD

**Issue by let4be** [lafikl/consistent#1]
What if 2 hosts will have the same fnv-1 hash?
https://github.com/lafikl/consistent/blob/master/consistent.go#L49

**Comment by lafikl** [comment]
Yeah, you're right.

Look at the new changes it should fix it.

**Comment by let4be** [comment]
This looks better. but still I'd double check the logic here
https://github.com/lafikl/consistent/blob/master/consistent.go#L55
you are using hash function output as a key to golang's map
depending on intended behavior this may be a bug(if collision happens)

consider super-host.com0 collides with super-host.com1 (collision would give them the same `h` value, this may seem unlikely but probability of this is > 0, I mean some host will collide for sure)
I guess if this happens we could get out-of-bounds afterwards as you access `hosts` by a dynamic index stored in `sortedSet`

**Comment by lafikl** [comment]
i changed the hashing algorithm to blake2 which should reduce the probability of collisions.

Also if a collision happen it'll not break the guarantees on the upper bound of load.
