### ISSUE TITLE
Inconsistent state on hash collision

### ISSUE THREAD

**Issue by LopatkinEvgeniy** [lafikl/consistent#10]
```go
//  Consistent.Add method
h := c.hash(fmt.Sprintf("%s%d", host, i))
c.hosts[h] = host
```
What will be if `c.hosts[h]` is not empty? When this host will be removed overridden host will not be restored. So Add/Remove of the same key may change internal state. I think this will break consistency. 

PS: Excuse my poor English

**Comment by hitzhangjie** [comment]
@LopatkinEvgeniy I think the collision cannot be avoided in this occasion, at least in current implemention of this project.

But it has another measures to reduce the `break consistency` problem, that is:

```
	for i := 0; i < replicationFactor; i++ {
		h := c.hash(fmt.Sprintf("%s%d", host, i))
		c.hosts[h] = host
		c.sortedSet = append(c.sortedSet, h)
	}
```

I think it is acceptable if other iterations succeed without collisions. Though this may be not meticulous or precise.

PS: Excuse my poor English, too.

**Comment by LopatkinEvgeniy** [comment]
Looks like that collision - it is super rare case
