### ISSUE TITLE
remove host from ring

### ISSUE THREAD

**Issue by tinytub** [lafikl/consistent#2]
https://github.com/lafikl/consistent/blob/6e1d11fbe827f49f9c37d1e6c96eea0372a3377b/consistent.go#L169

Remove host from ring,but didn't remove from loadmap.
If use Hosts() to get all hosts, it return the list generate from the loadmap, not real hosts in the ring.
Whether or not delete the host from loadmap ?

**Comment by lafikl** [comment]
yes you're right.

a PR to rectify this issue would be welcome.
