### ISSUE TITLE
ADD 需要加锁

### ISSUE THREAD

**Issue by hyhlinux** [lafikl/consistent#5]
1.consistance.add 

==================
WARNING: DATA RACE
Write at 0x00c42019c650 by goroutine 76:
  sync/atomic.AddInt64()
      /usr/local/Cellar/go/1.8.1/libexec/src/runtime/race_amd64.s:276 +0xb
  fs-router/vendor/github.com/lafikl/consistent.(*Consistent).Inc()
      /Users/apple/go-dev/src/fs-router/vendor/github.com/lafikl/consistent/consistent.go:149 +0xa8
  fs-router/controllers.getHost()
      /Users/apple/go-dev/src/fs-router/controllers/hashhost.go:185 +0x34b
  fs-router/controllers.load()
      /Users/apple/go-dev/src/fs-router/controllers/hashhost.go:200 +0xeb
  fs-router/controllers.HashHost()
      /Users/apple/go-dev/src/fs-router/controllers/hashhost.go:68 +0x3c
  fs-router/controllers.(*HostHashController).GetFileUrl()
      /Users/apple/go-dev/src/fs-router/controllers/host_grpc.go:15 +0xd0
  fs-router/protos._FileSystemRouterService_GetFileUrl_Handler()
      /Users/apple/go-dev/src/fs-router/protos/fs_router.pb.go:286 +0x35a
  fs-router/vendor/google.golang.org/grpc.(*Server).processUnaryRPC()
      /Users/apple/go-dev/src/fs-router/vendor/google.golang.org/grpc/server.go:776 +0x1221
  fs-router/vendor/google.golang.org/grpc.(*Server).handleStream()
      /Users/apple/go-dev/src/fs-router/vendor/google.golang.org/grpc/server.go:976 +0x150e
  fs-router/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /Users/apple/go-dev/src/fs-router/vendor/google.golang.org/grpc/server.go:546 +0xb6

**Comment by lafikl** [comment]
care to elaborate?
